<?php
include "sensorParser.php";

/**
 * Parser for CSV files generated by a GPS sensor
 */
class gpsParser extends sensorParser{
    //column index : FORMAT:  latitude, longitude, altitude, timestamp
    private $_LATITUDE = 0; private $_LONGITUDE = 1; private $_ALTITUDE = 2; private $_TIMESTAMP = 3;    

    /**
     * @overrides
     * @param type $row
     */
    protected function parseLine($db, $row, $user_id){
        $latitude = $row[$this->_LATITUDE];
        $longitude = $row[$this->_LONGITUDE];
        $altitude = $row[$this->_ALTITUDE];
        $timestamp = $row[$this->_TIMESTAMP];
          
        $db->insert("gps_sensor_data", array("latitude" => $latitude, "longitude" => $longitude, "altitude" => $altitude, "timestamp" => $timestamp, "user_id" => $user_id),'',array("float","float","float","float","integer"));
    }
}