<?php
include_once "sensorParser.php";
include_once "mining/GpsLog.php";

/**
 * Parser for CSV files generated by a GPS sensor
 */
class gpsParser extends sensorParser{
    /**
     * Re-implementation of parent's method. Delegate CSV parsing to GPS Log
     */
    public function parse(){
        $user_id = DataMapper::checkUser($this->username);
        
        $log = new GpsLog();
        $log->loadPointsFromCSV(UPLOAD_DIR.$this->filename);      
        //store gps points
        foreach($log->GetPoints() as $p)
            {DataMapper::SaveGpsPoint($p,$user_id);}
        //store stay points
        foreach($log->GetStayPoints() as $s)
            {DataMapper::SaveStayPoint($s, $user_id);}
            
        $this->eraseFiles($filename);
    }

    protected function parseLine($db, $data, $user_id) {
        //not used
    }

}