<?php
include "sensorParser.php";

/**
 * Parser for CSV files generated by a GPS sensor
 */
class gpsParser extends sensorParser{
    //column index : FORMAT:  latitude, longitude, altitude, timestamp
    private $_LATITUDE = 0; private $_LONGITUDE = 1; private $_ALTITUDE = 2; private $_TIMESTAMP = 3;    

    /**
     * @overrides
     * @param type $row
     */
    protected function parseLine($db, $row, $user_id){
        $latitude = $row[$this->_LATITUDE];
        $longitude = $row[$this->_LONGITUDE];
        $altitude = $row[$this->_ALTITUDE];
        $timestamp = $row[$this->_TIMESTAMP];        
        
        if(!$this->checkGpsPoint(null, $user_id, $timestamp)){
            $db = new DbAdapter(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);  
            $db->Insert("gps_sensor_data", array("latitude" => $latitude, "longitude" => $longitude, "altitude" => $altitude, "timestamp" => $timestamp, "user_id" => $user_id));
            $db->Close();
        }       
        
    }
    
    /**
     * Verifies if a stay point exists
     */
    protected function checkGpsPoint($db,$user_id, $timestamp){
        $db = new DbAdapter(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
        $point = $db->Get(TABLE_NAME, array("user_id" => "$user_id", "timestamp" => $timestamp));   
        $db->Close();
        if(isset($point[0]["id"])){
            return true;        
        }
        else{
            return false;            
        }
    }
}