<?php
include_once "MySql.php";
/**
 * Parser for CSV files generated by a sensor
 */
abstract class sensorParser{
    private $filename;
    private $user_id;
    private $uploads_dir;
    /**
     * Initialize filename
     * @param type $filename
     */
    public function __construct($filename, $user_id) {
        $this->filename = $filename;
        $this->user_id = $user_id;
    }
    /**
     * Specify search path for files
     * @param type $dir
     */
    public function setDir($dir){
        $this->uploads_dir = $dir;
    }    
    
    /**
     * Parse CSV and store in Database
     */
    public function parse(){
        try{
            if($this->filename){
                //echo "Processing file:".$this->filename;
                $filename = $this->filename;
                $uploads_dir = $this->uploads_dir;
                if (($handle = fopen("$uploads_dir/$filename", "r")) !== FALSE) {
                    while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
                        $this->parseLine($data, $this->user_id);
                    }
                    fclose($handle);
                }
                //unlink("$uploads_dir/$filename");
                echo $this->filename." uploaded OK!";
            }else{
            echo "not found:".$this->filename;}
        }catch(Exception $e){
            echo "ERROR uploading ".$this->filename;
        }
    }
    /**
     * To be implemented for each type of sensor (instructions to parse each line)
     */
    abstract protected function parseLine($data, $user_id);
}