<?php
include_once "sensorParser.php";


/**
 * Parser for CSV files generated by a battery pseudo sensor
 */
class stayPointParser extends sensorParser{
    //column index : FORMAT:  charging, usb, ac, level, timestamp
    private $_avg_longitude = 0; private $_avg_latitude= 1; private $_arrival = 2; 
    private $_departure = 3; private $_cardinality = 4; private $_label = 5; 
    private $_start_longitude = 6; private $_start_latitude = 7;  private $_client_id = 8;

    /**
     * Parse stay_points.csv file
     * @param type $eraseFiles
     */
    public function parse($eraseFiles = true) {
        $user_id = "1"; 
        if($this->filename){    
            $user_id = DataMapper::checkUser($this->username);            
            $filename = $this->filename;
            if (($handle = fopen(UPLOAD_DIR."$filename", "r")) !== FALSE) {
                while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {  
                    $this->parseLine(null,$data, $user_id);     
                }                    
            }
            fclose($handle);
            if($eraseFiles) {$this->eraseFiles($filename);}
            echo $this->filename." uploaded OK!";
        }  else {
            echo "No stay points file found!";
        }
    }
    
    /**
     * @overrides
     * @param type $row
     */
    protected function parseLine($db,$row, $user_id){
        $_avg_longitude = $row[$this->_avg_longitude];  $_avg_latitude= $row[$this->_avg_latitude];  $_arrival = $row[$this->_arrival]; 
        $_departure = $row[$this->_departure];  $_cardinality = $row[$this->_cardinality];  $_label = $row[$this->_label]; 
        $_start_longitude = $row[$this->_start_longitude];  $_start_latitude = $row[$this->_start_latitude]; $client_id = $row[$this->_client_id];

        $db = new DbAdapter(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
        if(!$this->checkPoint(null, $user_id, $client_id)){
      echo "Cloud Server: stay added.\n";
           $db->Insert(TABLE_NAME, array("avg_latitude" => $_avg_latitude, "avg_longitude" => $_avg_longitude, 
               "arrival" => $_arrival, "departure" => $_departure, "cardinality" => $_cardinality, "label" => $_label,
               "start_longitude" => $_start_longitude,"start_latitude" => $_start_latitude, "user_id" => $user_id, "client_id" => $client_id));
        }else{
            echo "Cloud Server: stay updated.\n";
            $db->Update(TABLE_NAME, array("departure" => $_departure, "cardinality" => $_cardinality, "avg_longitude" => $_avg_longitude, "avg_latitude" => $_avg_latitude), array("client_id" => $client_id, "user_id" => $user_id));
        }
        $db->Close();
    }
    
    /**
     * Verifies if a stay point exists
     */
    protected function checkPoint($db,$user_id, $client_id){
        $db = new DbAdapter(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
        $point = $db->Get(TABLE_NAME, array("user_id" => "$user_id", "client_id" => $client_id));   
        $db->Close();
        if(isset($point[0]["id"])){
            return true;        
        }
        else{
            return false;            
        }
    }
}