<?php
include_once "sensorParser.php";

/**
 * Parser for CSV files generated by a wifi pseudo sensor
 */
class wifiParser extends sensorParser{
    //column index : FORMAT:  status,ssid, timestamp
    private $_STATUS = 0; private $_SSID = 1; private $_TIMESTAMP = 2;    

    /**
     * @overrides
     * @param array $row
     * @param int $user_id
     */
    protected function parseLine($db,$row, $user_id){
        $status = $row[$this->_STATUS];
        $ssid = $row[$this->_SSID];
        $timestamp = $row[$this->_TIMESTAMP];

        $db->insert("wifi_sensor_data", array("status" => $status, "ssid" => $ssid, "timestamp" => $timestamp, "user_id" => $user_id),'',array("integer","string","float", "integer"));
    }
}